name: "Push_workflow"
on:
    push:
        branches:
            - main
jobs:
    first-job: 
        runs-on: ubuntu-latest
        steps:
            - name: Print Greetings
              run: echo "Welcome to Blinkit"
            - name: Print Goodbye
              run: |
                   echo ""Go to cart"
                   echo "Order placed Successfully"
